import {expect, test} from '../../test'

describe('command', () => {
  test
  .command(['plugins:install', 'status'])
  .stdout()
  .command(['plugins'])
  .do(output => expect(output.stdout).to.contain('status '))
  .stdout()
  .command(['status'])
  .do(output => expect(output.stdout).to.contain('No known issues at this time'))
  .command(['plugins:uninstall', '@heroku-cli/status-plugin'])
  .stdout()
  .command(['plugins'])
  .do(output => expect(output.stdout).to.equal('no plugins installed\n'))
  .it('installs and uninstalls status')

  test
  .command(['plugins:install', '@heroku-cli/status-plugin'])
  .stdout()
  .command(['plugins'])
  .do(output => expect(output.stdout).to.contain('status '))
  .stdout()
  .command(['status'])
  .do(output => expect(output.stdout).to.contain('No known issues at this time'))
  .command(['plugins:uninstall', 'status'])
  .stdout()
  .command(['plugins'])
  .do(output => expect(output.stdout).to.equal('no plugins installed\n'))
  .it('installs and uninstalls @heroku-cli/status-plugin')

  test
  .skip()
  .command(['plugins:install', 'heroku-debug'])
  .stdout()
  .command(['plugins'])
  .do(output => expect(output.stdout).to.contain('heroku-debug'))
  .stdout()
  .command(['debug'])
  .do(output => expect(output.stdout).to.contain('foo'))
  .command(['plugins:uninstall', 'heroku-debug'])
  .stdout()
  .command(['plugins'])
  .do(output => expect(output.stdout).to.equal('no plugins installed\n'))
  .it('installs and uninstalls heroku-debug')
})
